[package]
name = "dev_caloptreyx_playermanager"
description = "Manage the players of Minecraft Java and Bedrock servers: online players, whitelist, operators, bans and Java player profiles."
authors = ["Caloptreyx"]
version = "0.1.0"
edition = { workspace = true }

[dependencies]
shared = { workspace = true }
wings-api = { workspace = true }
async-trait = { workspace = true }
tracing = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
utoipa = { workspace = true }
utoipa-axum = { workspace = true }
axum = { workspace = true }
compact_str = { workspace = true }
reqwest = { workspace = true }
uuid = { workspace = true }
chrono = { workspace = true }
tokio = { workspace = true }
regex = { workspace = true }
md5 = "0.8"
flate2 = "1.1"
